{
 "title": "Wavespeed.ai statistic",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Balance now",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "wavespeed_balance_usd", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Balance",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 14, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    { "expr": "wavespeed_balance_usd", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Daily expenses",
   "type": "table",
   "gridPos": { "h": 9, "w": 5, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "max by (date,model_type) (\n  wavespeed_daily_usage{\n    metric=\"cost_usd\", model_type=\"\"\n  }\n)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Daily generations",
   "type": "table",
   "gridPos": { "h": 9, "w": 5, "x": 5, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max by (date) (\n  wavespeed_daily_usage{\n    metric=\"count\",\n    model_type=\"\"\n  }\n)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Daily expenses per type",
   "type": "table",
   "gridPos": { "h": 18, "w": 7, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "max by (date, model_type) (\n  wavespeed_daily_usage{\n    metric=\"cost_usd\",\n    model_uuid=~\".+\"\n  }\n)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Daily expenses per model",
   "type": "table",
   "gridPos": { "h": 18, "w": 11, "x": 7, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "max by (date, model_uuid) (\n  wavespeed_daily_usage{\n    metric=\"cost_usd\",\n    model_uuid=~\".+\"\n  }\n)\n",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}